[package]
name = "WrappedCoin"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies]
MoveStdlib = { git = "https://github.com/cedra-labs/cedra-network.git", subdir = "cedra-move/framework/move-stdlib/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }

[dev-addresses]
wrapped_coin = "0xBEEF"

[addresses]
wrapped_coin = "_"
