[package]
name = "Wormhole"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-network.git", subdir = "cedra-move/framework/cedra-framework/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
MoveStdlib = { git = "https://github.com/cedra-labs/cedra-network.git", subdir = "cedra-move/framework/move-stdlib/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
CedraStdlib = { git = "https://github.com/cedra-labs/cedra-network.git", subdir = "cedra-move/framework/cedra-stdlib/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
CedraToken = { git = "https://github.com/cedra-labs/cedra-network.git", subdir = "cedra-move/framework/cedra-token/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
Deployer = { git = "https://github.com/cedra-labs/cedra-package-deployer.git", rev = "259ef0d2fd1e66413d57a52965c8bc239e939489" }

[dev-dependencies]
Deployer = { git = "https://github.com/cedra-labs/cedra-package-deployer.git", rev = "259ef0d2fd1e66413d57a52965c8bc239e939489" }

[dev-addresses]
# derived address from sha3_256(deployer | "wormhole" | 0xFF) by running
# worm cedra derive-resource-account 0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b wormhole
wormhole = "0xde0036a9600559e295d5f6802ef6f3f802f510366e0c23912b0655d972166017"
deployer = "0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"

[addresses]
wormhole = "_"
